import '../models/nation.dart';

class GlobeContent {
  static List<Nation> get allNations => [..._africa,..._americas,..._asia,..._europe,..._oceania];

  static List<Nation> nationsFor(GlobeRegion region) {
    switch(region){
      case GlobeRegion.africa: return _africa;
      case GlobeRegion.americas: return _americas;
      case GlobeRegion.asia: return _asia;
      case GlobeRegion.europe: return _europe;
      case GlobeRegion.oceania: return _oceania;
    }
  }

  static const _africa = [
    Nation(id:'ng',name:'Nigeria',emoji:'🇳🇬',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Nigeria?',type:ChallengeType.mcq,answer:'Abuja',options:['Lagos','Abuja','Kano','Ibadan']),
      Challenge(text:'Nigeria is the most populous country on which continent?',type:ChallengeType.mcq,answer:'Africa',options:['Asia','South America','Africa','Europe']),
      Challenge(text:'What is the currency of Nigeria?',type:ChallengeType.mcq,answer:'Naira',options:['Cedi','Naira','Franc','Shilling']),
      Challenge(text:'What major river flows through Nigeria?',type:ChallengeType.typeIn,answer:'Niger',hint:'Same as the country name'),
      Challenge(text:'What is the largest city in Nigeria by population?',type:ChallengeType.typeIn,answer:'Lagos',hint:'Former capital, coastal city'),
    ]),
    Nation(id:'ke',name:'Kenya',emoji:'🇰🇪',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Kenya?',type:ChallengeType.mcq,answer:'Nairobi',options:['Mombasa','Kisumu','Nairobi','Nakuru']),
      Challenge(text:'Kenya is famous for which annual migration?',type:ChallengeType.mcq,answer:'Great Wildebeest Migration',options:['Elephant March','Great Wildebeest Migration','Zebra Run','Flamingo Flight']),
      Challenge(text:'What is the official language of Kenya alongside Swahili?',type:ChallengeType.mcq,answer:'English',options:['French','Arabic','English','Portuguese']),
      Challenge(text:'What is Africa\'s second highest mountain, in Kenya?',type:ChallengeType.typeIn,answer:'Mount Kenya',hint:'The country is named after it'),
      Challenge(text:'What ocean borders Kenya to the east?',type:ChallengeType.typeIn,answer:'Indian Ocean',hint:'Warm waters, home to Mombasa port'),
    ]),
    Nation(id:'za',name:'South Africa',emoji:'🇿🇦',region:GlobeRegion.africa,challenges:[
      Challenge(text:'How many capital cities does South Africa have?',type:ChallengeType.mcq,answer:'Three',options:['One','Two','Three','Four']),
      Challenge(text:'What is the currency of South Africa?',type:ChallengeType.mcq,answer:'Rand',options:['Pula','Kwacha','Rand','Shilling']),
      Challenge(text:'Which city is known as South Africa\'s "Mother City"?',type:ChallengeType.mcq,answer:'Cape Town',options:['Johannesburg','Durban','Cape Town','Pretoria']),
      Challenge(text:'Who was South Africa\'s first democratically elected president?',type:ChallengeType.typeIn,answer:'Nelson Mandela',hint:'Nobel Peace Prize winner'),
      Challenge(text:'What flat-topped mountain overlooks Cape Town?',type:ChallengeType.typeIn,answer:'Table Mountain',hint:'Often covered in cloud'),
    ]),
    Nation(id:'eg',name:'Egypt',emoji:'🇪🇬',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What ancient wonder is located near Giza, Egypt?',type:ChallengeType.mcq,answer:'Great Pyramid',options:['Colosseum','Great Wall','Great Pyramid','Taj Mahal']),
      Challenge(text:'What river runs through Egypt?',type:ChallengeType.mcq,answer:'Nile',options:['Congo','Zambezi','Nile','Niger']),
      Challenge(text:'What is the capital of Egypt?',type:ChallengeType.mcq,answer:'Cairo',options:['Alexandria','Luxor','Aswan','Cairo']),
      Challenge(text:'What ancient Egyptian writing system used picture symbols?',type:ChallengeType.typeIn,answer:'Hieroglyphics',hint:'Picture-based ancient script'),
      Challenge(text:'What sea borders Egypt to the north?',type:ChallengeType.typeIn,answer:'Mediterranean Sea',hint:'Connects Africa to Europe'),
    ]),
    Nation(id:'gh',name:'Ghana',emoji:'🇬🇭',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Ghana?',type:ChallengeType.mcq,answer:'Accra',options:['Kumasi','Tamale','Accra','Takoradi']),
      Challenge(text:'Ghana gained independence from Britain in which year?',type:ChallengeType.mcq,answer:'1957',options:['1947','1957','1963','1975']),
      Challenge(text:'Ghana is a top producer of which cash crop?',type:ChallengeType.mcq,answer:'Cocoa',options:['Coffee','Cocoa','Tea','Sugar']),
      Challenge(text:'What former name was Ghana known by under British rule?',type:ChallengeType.typeIn,answer:'Gold Coast',hint:'Named for its gold trade'),
      Challenge(text:'What is the currency of Ghana?',type:ChallengeType.typeIn,answer:'Cedi',hint:'Means "cowrie shell" in Akan'),
    ]),
    Nation(id:'et',name:'Ethiopia',emoji:'🇪🇹',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Ethiopia?',type:ChallengeType.mcq,answer:'Addis Ababa',options:['Dire Dawa','Gondar','Hawassa','Addis Ababa']),
      Challenge(text:'Ethiopia is the origin of which beloved beverage?',type:ChallengeType.mcq,answer:'Coffee',options:['Tea','Coffee','Cocoa','Beer']),
      Challenge(text:'Ethiopia was briefly occupied by which European country?',type:ChallengeType.mcq,answer:'Italy',options:['Britain','France','Italy','Portugal']),
      Challenge(text:'What ancient kingdom ruled northern Ethiopia for centuries?',type:ChallengeType.typeIn,answer:'Aksum',hint:'Also spelled Axum'),
      Challenge(text:'What "Jade Sea" lake is found in Ethiopia\'s Rift Valley?',type:ChallengeType.typeIn,answer:'Lake Turkana',hint:'World\'s largest permanent desert lake'),
    ]),
    Nation(id:'tz',name:'Tanzania',emoji:'🇹🇿',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is Africa\'s highest mountain, in Tanzania?',type:ChallengeType.mcq,answer:'Kilimanjaro',options:['Mount Kenya','Rwenzori','Kilimanjaro','Atlas']),
      Challenge(text:'What is the capital of Tanzania?',type:ChallengeType.mcq,answer:'Dodoma',options:['Dar es Salaam','Dodoma','Zanzibar','Arusha']),
      Challenge(text:'Which island off Tanzania is famous for its spice trade?',type:ChallengeType.mcq,answer:'Zanzibar',options:['Pemba','Zanzibar','Mafia','Kilwa']),
      Challenge(text:'What vast conservation area in Tanzania is world-famous for wildlife?',type:ChallengeType.typeIn,answer:'Serengeti',hint:'Famous for endless plains and wildebeest'),
      Challenge(text:'What ocean borders Tanzania to the east?',type:ChallengeType.typeIn,answer:'Indian Ocean',hint:'Warm waters shared with Kenya'),
    ]),
    Nation(id:'ma',name:'Morocco',emoji:'🇲🇦',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Morocco?',type:ChallengeType.mcq,answer:'Rabat',options:['Casablanca','Marrakech','Fez','Rabat']),
      Challenge(text:'Which mountain range runs through Morocco?',type:ChallengeType.mcq,answer:'Atlas Mountains',options:['Sahara Hills','Atlas Mountains','Rif Mountains','Draâ Range']),
      Challenge(text:'Morocco borders which European country to the north?',type:ChallengeType.mcq,answer:'Spain',options:['Portugal','France','Spain','Gibraltar']),
      Challenge(text:'What is Morocco\'s most-visited ancient medina city?',type:ChallengeType.typeIn,answer:'Marrakech',hint:'Known as the Red City'),
      Challenge(text:'What is the currency of Morocco?',type:ChallengeType.typeIn,answer:'Dirham',hint:'Abbreviated MAD'),
    ]),
    Nation(id:'sn',name:'Senegal',emoji:'🇸🇳',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Senegal?',type:ChallengeType.mcq,answer:'Dakar',options:['Thiès','Saint-Louis','Ziguinchor','Dakar']),
      Challenge(text:'Senegal almost entirely surrounds which country?',type:ChallengeType.mcq,answer:'Gambia',options:['Guinea','Guinea-Bissau','Gambia','Mali']),
      Challenge(text:'What is the official language of Senegal?',type:ChallengeType.mcq,answer:'French',options:['English','Wolof','French','Arabic']),
      Challenge(text:'What UNESCO island off Dakar was a slave trade hub?',type:ChallengeType.typeIn,answer:'Gorée Island',hint:'UNESCO World Heritage Site'),
      Challenge(text:'What currency do Senegal and many West African nations share?',type:ChallengeType.typeIn,answer:'CFA Franc',hint:'Shared currency across the region'),
    ]),
    Nation(id:'cm',name:'Cameroon',emoji:'🇨🇲',region:GlobeRegion.africa,challenges:[
      Challenge(text:'Why is Cameroon called "Africa in miniature"?',type:ChallengeType.mcq,answer:'Diverse landscapes',options:['Large size','Diverse languages','Diverse landscapes','Rich gold']),
      Challenge(text:'What is the capital of Cameroon?',type:ChallengeType.mcq,answer:'Yaoundé',options:['Douala','Bamenda','Yaoundé','Bafoussam']),
      Challenge(text:'Cameroon has official status in how many languages?',type:ChallengeType.mcq,answer:'Two',options:['One','Two','Three','Four']),
      Challenge(text:'What is West Africa\'s highest peak, found in Cameroon?',type:ChallengeType.typeIn,answer:'Mount Cameroon',hint:'Also one of Africa\'s most active volcanoes'),
      Challenge(text:'What lake borders Cameroon, Nigeria, Chad, and Niger?',type:ChallengeType.typeIn,answer:'Lake Chad',hint:'Shrinking due to climate change'),
    ]),
    Nation(id:'ci',name:'Ivory Coast',emoji:'🇨🇮',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Ivory Coast?',type:ChallengeType.mcq,answer:'Yamoussoukro',options:['Abidjan','San-Pédro','Yamoussoukro','Bouaké']),
      Challenge(text:'Ivory Coast is the world\'s largest producer of which crop?',type:ChallengeType.mcq,answer:'Cocoa',options:['Coffee','Palm Oil','Cocoa','Rubber']),
      Challenge(text:'What is Ivory Coast\'s French name?',type:ChallengeType.mcq,answer:'Côte d\'Ivoire',options:['Costa Marfil','Côte d\'Ivoire','Terre Ivoire','Bord d\'Ivoire']),
      Challenge(text:'What is the largest city and economic capital of Ivory Coast?',type:ChallengeType.typeIn,answer:'Abidjan',hint:'Major port city, former capital'),
      Challenge(text:'What gulf borders Ivory Coast to the south?',type:ChallengeType.typeIn,answer:'Gulf of Guinea',hint:'Part of the Atlantic Ocean'),
    ]),
    Nation(id:'ug',name:'Uganda',emoji:'🇺🇬',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Uganda?',type:ChallengeType.mcq,answer:'Kampala',options:['Entebbe','Gulu','Jinja','Kampala']),
      Challenge(text:'Uganda is home to half the world\'s mountain gorillas. True or False?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What lake provides Uganda\'s southern border?',type:ChallengeType.mcq,answer:'Lake Victoria',options:['Lake Albert','Lake Edward','Lake Victoria','Lake Kyoga']),
      Challenge(text:'What is the source of the Nile River found in Uganda?',type:ChallengeType.typeIn,answer:'Lake Victoria',hint:'Africa\'s largest lake'),
      Challenge(text:'What is the currency of Uganda?',type:ChallengeType.typeIn,answer:'Ugandan Shilling',hint:'Abbreviated UGX'),
    ]),
    Nation(id:'zm',name:'Zambia',emoji:'🇿🇲',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Zambia?',type:ChallengeType.mcq,answer:'Lusaka',options:['Ndola','Livingstone','Kitwe','Lusaka']),
      Challenge(text:'What famous waterfall lies on Zambia\'s border with Zimbabwe?',type:ChallengeType.mcq,answer:'Victoria Falls',options:['Kalambo Falls','Victoria Falls','Kundalila Falls','Chavuma Falls']),
      Challenge(text:'Zambia is a leading producer of which metal?',type:ChallengeType.mcq,answer:'Copper',options:['Gold','Copper','Cobalt','Zinc']),
      Challenge(text:'What is the local name for Victoria Falls meaning "smoke that thunders"?',type:ChallengeType.typeIn,answer:'Mosi-oa-Tunya',hint:'Tonga language'),
      Challenge(text:'What is the currency of Zambia?',type:ChallengeType.typeIn,answer:'Kwacha',hint:'Means "dawn" in Bemba'),
    ]),
    Nation(id:'rw',name:'Rwanda',emoji:'🇷🇼',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Rwanda?',type:ChallengeType.mcq,answer:'Kigali',options:['Butare','Gisenyi','Ruhengeri','Kigali']),
      Challenge(text:'Rwanda is nicknamed what for its thousands of hills?',type:ChallengeType.mcq,answer:'Land of a Thousand Hills',options:['Land of Lakes','Land of Gorillas','Land of a Thousand Hills','Pearl of Africa']),
      Challenge(text:'In which year did the Rwandan genocide occur?',type:ChallengeType.mcq,answer:'1994',options:['1984','1990','1994','2000']),
      Challenge(text:'What park in Rwanda is famous for endangered mountain gorillas?',type:ChallengeType.typeIn,answer:'Volcanoes National Park',hint:'Northwest near the Congo border'),
      Challenge(text:'What is the currency of Rwanda?',type:ChallengeType.typeIn,answer:'Rwandan Franc',hint:'Abbreviated RWF'),
    ]),
    Nation(id:'ml',name:'Mali',emoji:'🇲🇱',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Mali?',type:ChallengeType.mcq,answer:'Bamako',options:['Timbuktu','Gao','Mopti','Bamako']),
      Challenge(text:'Mali contains a large portion of which great desert?',type:ChallengeType.mcq,answer:'Sahara',options:['Kalahari','Namib','Sahara','Arabian']),
      Challenge(text:'Which ancient trading city in Mali was a centre of Islamic scholarship?',type:ChallengeType.mcq,answer:'Timbuktu',options:['Djenné','Gao','Timbuktu','Mopti']),
      Challenge(text:'What river flows through Mali and is critical for agriculture?',type:ChallengeType.typeIn,answer:'Niger',hint:'Same name as a neighbouring country'),
      Challenge(text:'What ancient mosque in Djenné, Mali is the world\'s largest mud-brick building?',type:ChallengeType.typeIn,answer:'Great Mosque of Djenné',hint:'UNESCO World Heritage Site'),
    ]),
    Nation(id:'mg',name:'Madagascar',emoji:'🇲🇬',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Madagascar?',type:ChallengeType.mcq,answer:'Antananarivo',options:['Toamasina','Mahajanga','Antananarivo','Fianarantsoa']),
      Challenge(text:'Madagascar is the world\'s fourth largest what?',type:ChallengeType.mcq,answer:'Island',options:['Country','Lake','Desert','Island']),
      Challenge(text:'What unique primate is Madagascar most famous for?',type:ChallengeType.mcq,answer:'Lemurs',options:['Lemurs','Chameleons','Tortoises','Baobabs']),
      Challenge(text:'What ocean surrounds Madagascar?',type:ChallengeType.typeIn,answer:'Indian Ocean',hint:'Warm ocean east of Africa'),
      Challenge(text:'What is the currency of Madagascar?',type:ChallengeType.typeIn,answer:'Ariary',hint:'Abbreviated MGA'),
    ]),
    Nation(id:'dz',name:'Algeria',emoji:'🇩🇿',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Algeria?',type:ChallengeType.mcq,answer:'Algiers',options:['Oran','Constantine','Algiers','Annaba']),
      Challenge(text:'Algeria is the largest country by area on which continent?',type:ChallengeType.mcq,answer:'Africa',options:['Asia','South America','Africa','Australia']),
      Challenge(text:'What desert covers most of Algeria?',type:ChallengeType.mcq,answer:'Sahara',options:['Namib','Sahara','Kalahari','Arabian']),
      Challenge(text:'What is the official language of Algeria?',type:ChallengeType.typeIn,answer:'Arabic',hint:'Also widely spoken: French and Tamazight'),
      Challenge(text:'What is the currency of Algeria?',type:ChallengeType.typeIn,answer:'Algerian Dinar',hint:'Abbreviated DZD'),
    ]),
    Nation(id:'tn',name:'Tunisia',emoji:'🇹🇳',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Tunisia?',type:ChallengeType.mcq,answer:'Tunis',options:['Sfax','Sousse','Kairouan','Tunis']),
      Challenge(text:'Tunisia was home to which ancient city that rivalled Rome?',type:ChallengeType.mcq,answer:'Carthage',options:['Utica','Carthage','Thysdrus','Sufetula']),
      Challenge(text:'Which sea borders Tunisia to the north?',type:ChallengeType.mcq,answer:'Mediterranean Sea',options:['Red Sea','Black Sea','Mediterranean Sea','Adriatic Sea']),
      Challenge(text:'Star Wars desert scenes were filmed in which Tunisian location?',type:ChallengeType.typeIn,answer:'Matmata',hint:'Famous for troglodyte cave dwellings'),
      Challenge(text:'What is the currency of Tunisia?',type:ChallengeType.typeIn,answer:'Tunisian Dinar',hint:'Abbreviated TND'),
    ]),
    Nation(id:'ao',name:'Angola',emoji:'🇦🇴',region:GlobeRegion.africa,challenges:[
      Challenge(text:'What is the capital of Angola?',type:ChallengeType.mcq,answer:'Luanda',options:['Huambo','Lubango','Benguela','Luanda']),
      Challenge(text:'Angola is a major producer of which two resources?',type:ChallengeType.mcq,answer:'Oil and Diamonds',options:['Gold and Coffee','Oil and Diamonds','Coal and Iron','Copper and Cocoa']),
      Challenge(text:'What is the official language of Angola?',type:ChallengeType.mcq,answer:'Portuguese',options:['English','Spanish','Portuguese','French']),
      Challenge(text:'What is the currency of Angola?',type:ChallengeType.typeIn,answer:'Kwanza',hint:'Abbreviated AOA'),
      Challenge(text:'What ocean borders Angola to the west?',type:ChallengeType.typeIn,answer:'Atlantic Ocean',hint:'The western ocean of Africa'),
    ]),
  ];

  static const _americas = [
    Nation(id:'br',name:'Brazil',emoji:'🇧🇷',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Brazil?',type:ChallengeType.mcq,answer:'Brasília',options:['São Paulo','Rio de Janeiro','Brasília','Salvador']),
      Challenge(text:'The Amazon River empties into which ocean?',type:ChallengeType.mcq,answer:'Atlantic Ocean',options:['Pacific Ocean','Indian Ocean','Atlantic Ocean','Caribbean Sea']),
      Challenge(text:'Brazil is the only Portuguese-speaking country in South America. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What city is famous for Brazil\'s annual carnival?',type:ChallengeType.typeIn,answer:'Rio de Janeiro',hint:'Home of the Sambadrome parade'),
      Challenge(text:'What is the currency of Brazil?',type:ChallengeType.typeIn,answer:'Real',hint:'Abbreviated BRL'),
    ]),
    Nation(id:'mx',name:'Mexico',emoji:'🇲🇽',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Mexico?',type:ChallengeType.mcq,answer:'Mexico City',options:['Guadalajara','Monterrey','Mexico City','Puebla']),
      Challenge(text:'Mexico was the heartland of which ancient civilisation?',type:ChallengeType.mcq,answer:'Aztec',options:['Maya','Aztec','Inca','Olmec']),
      Challenge(text:'What is the currency of Mexico?',type:ChallengeType.mcq,answer:'Peso',options:['Real','Quetzal','Peso','Colón']),
      Challenge(text:'What southern peninsula of Mexico is home to Chichén Itzá?',type:ChallengeType.typeIn,answer:'Yucatán',hint:'Home of Mayan ruins and Caribbean beaches'),
      Challenge(text:'What chilli-chocolate sauce is a staple of Mexican cuisine?',type:ChallengeType.typeIn,answer:'Mole',hint:'Dark complex sauce from Oaxaca'),
    ]),
    Nation(id:'co',name:'Colombia',emoji:'🇨🇴',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Colombia?',type:ChallengeType.mcq,answer:'Bogotá',options:['Medellín','Cali','Cartagena','Bogotá']),
      Challenge(text:'Colombia has coastlines on the Pacific and which other body of water?',type:ChallengeType.mcq,answer:'Caribbean Sea',options:['Gulf of Mexico','Caribbean Sea','Atlantic only','South Atlantic']),
      Challenge(text:'Colombia is the world\'s largest exporter of which flower product?',type:ChallengeType.mcq,answer:'Cut flowers',options:['Roses only','Orchids only','Cut flowers','Sunflowers']),
      Challenge(text:'What is the currency of Colombia?',type:ChallengeType.typeIn,answer:'Peso',hint:'Abbreviated COP'),
      Challenge(text:'What pre-Columbian archaeological park in Huila is a UNESCO site?',type:ChallengeType.typeIn,answer:'San Agustín',hint:'Famous for giant stone statues'),
    ]),
    Nation(id:'ar',name:'Argentina',emoji:'🇦🇷',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Argentina?',type:ChallengeType.mcq,answer:'Buenos Aires',options:['Córdoba','Rosario','Mendoza','Buenos Aires']),
      Challenge(text:'What dramatic natural region covers southern Argentina?',type:ChallengeType.mcq,answer:'Patagonia',options:['Pampas','Patagonia','Gran Chaco','Atacama']),
      Challenge(text:'What famous dance originated in Argentina?',type:ChallengeType.mcq,answer:'Tango',options:['Samba','Salsa','Tango','Cumbia']),
      Challenge(text:'What is the currency of Argentina?',type:ChallengeType.typeIn,answer:'Peso',hint:'Abbreviated ARS'),
      Challenge(text:'What are Argentine cowboys of the pampas called?',type:ChallengeType.typeIn,answer:'Gauchos',hint:'South American cowboys'),
    ]),
    Nation(id:'pe',name:'Peru',emoji:'🇵🇪',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Peru?',type:ChallengeType.mcq,answer:'Lima',options:['Cusco','Arequipa','Trujillo','Lima']),
      Challenge(text:'What ancient Incan citadel is in the Andes of Peru?',type:ChallengeType.mcq,answer:'Machu Picchu',options:['Chichén Itzá','Tiwanaku','Machu Picchu','Sacsayhuamán']),
      Challenge(text:'What is the world\'s highest navigable lake, shared by Peru and Bolivia?',type:ChallengeType.mcq,answer:'Lake Titicaca',options:['Lake Titicaca','Lake Junín','Lake Poopó','Laguna Colorada']),
      Challenge(text:'What is the currency of Peru?',type:ChallengeType.typeIn,answer:'Sol',hint:'Abbreviated PEN, means "sun"'),
      Challenge(text:'What ancient civilisation built Machu Picchu?',type:ChallengeType.typeIn,answer:'Inca',hint:'Their empire was called Tawantinsuyu'),
    ]),
    Nation(id:'ve',name:'Venezuela',emoji:'🇻🇪',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Venezuela?',type:ChallengeType.mcq,answer:'Caracas',options:['Maracaibo','Valencia','Barquisimeto','Caracas']),
      Challenge(text:'What is the world\'s highest uninterrupted waterfall, in Venezuela?',type:ChallengeType.mcq,answer:'Angel Falls',options:['Niagara Falls','Angel Falls','Iguazú Falls','Kaieteur Falls']),
      Challenge(text:'Venezuela borders which body of water to the north?',type:ChallengeType.mcq,answer:'Caribbean Sea',options:['Atlantic Ocean','Pacific Ocean','Caribbean Sea','Gulf of Mexico']),
      Challenge(text:'What is the currency of Venezuela?',type:ChallengeType.typeIn,answer:'Bolívar',hint:'Named after independence hero Simón Bolívar'),
      Challenge(text:'What vast tropical grasslands cover central Venezuela?',type:ChallengeType.typeIn,answer:'Llanos',hint:'Seasonal wetlands teeming with wildlife'),
    ]),
    Nation(id:'cl',name:'Chile',emoji:'🇨🇱',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Chile?',type:ChallengeType.mcq,answer:'Santiago',options:['Valparaíso','Concepción','Santiago','Antofagasta']),
      Challenge(text:'Chile is the world\'s longest country north-to-south at approximately?',type:ChallengeType.mcq,answer:'4,300 km',options:['2,100 km','4,300 km','6,000 km','3,000 km']),
      Challenge(text:'The Atacama Desert in northern Chile is the driest non-polar desert on Earth. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Chile?',type:ChallengeType.typeIn,answer:'Peso',hint:'Abbreviated CLP'),
      Challenge(text:'What remote Chilean island has moai stone statues?',type:ChallengeType.typeIn,answer:'Easter Island',hint:'Also called Rapa Nui'),
    ]),
    Nation(id:'ec',name:'Ecuador',emoji:'🇪🇨',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Ecuador?',type:ChallengeType.mcq,answer:'Quito',options:['Guayaquil','Cuenca','Quito','Loja']),
      Challenge(text:'Ecuador is named after which geographical feature?',type:ChallengeType.mcq,answer:'The Equator',options:['A river','The Equator','The Andes','A native tribe']),
      Challenge(text:'The Galápagos Islands belong to which country?',type:ChallengeType.mcq,answer:'Ecuador',options:['Peru','Colombia','Ecuador','Panama']),
      Challenge(text:'What currency does Ecuador use?',type:ChallengeType.typeIn,answer:'US Dollar',hint:'Ecuador adopted this foreign currency'),
      Challenge(text:'What active volcano near Quito is one of the world\'s highest?',type:ChallengeType.typeIn,answer:'Cotopaxi',hint:'Part of the "Avenue of the Volcanoes"'),
    ]),
    Nation(id:'bo',name:'Bolivia',emoji:'🇧🇴',region:GlobeRegion.americas,challenges:[
      Challenge(text:'Bolivia has two capitals. What is the seat of government?',type:ChallengeType.mcq,answer:'La Paz',options:['Sucre','Santa Cruz','La Paz','Cochabamba']),
      Challenge(text:'What is the world\'s largest salt flat, found in Bolivia?',type:ChallengeType.mcq,answer:'Salar de Uyuni',options:['Salar de Uyuni','Atacama Flats','Chott el Djerid','Bonneville']),
      Challenge(text:'Bolivia and which other country are South America\'s only landlocked nations?',type:ChallengeType.mcq,answer:'Paraguay',options:['Uruguay','Paraguay','Ecuador','Venezuela']),
      Challenge(text:'What is the currency of Bolivia?',type:ChallengeType.typeIn,answer:'Boliviano',hint:'Abbreviated BOB'),
      Challenge(text:'What ancient city on Lake Titicaca\'s shore was Bolivia\'s pre-Incan centre?',type:ChallengeType.typeIn,answer:'Tiwanaku',hint:'Also spelled Tiahuanaco'),
    ]),
    Nation(id:'cu',name:'Cuba',emoji:'🇨🇺',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Cuba?',type:ChallengeType.mcq,answer:'Havana',options:['Santiago de Cuba','Trinidad','Havana','Camagüey']),
      Challenge(text:'Cuba is the largest island in which sea?',type:ChallengeType.mcq,answer:'Caribbean Sea',options:['Gulf of Mexico','Atlantic Ocean','Caribbean Sea','Pacific Ocean']),
      Challenge(text:'Cuba is famous for which hand-rolled tobacco product?',type:ChallengeType.mcq,answer:'Cigars',options:['Cigarettes','Cigars','Pipe tobacco','Chewing tobacco']),
      Challenge(text:'What is the currency of Cuba?',type:ChallengeType.typeIn,answer:'Cuban Peso',hint:'Abbreviated CUP'),
      Challenge(text:'What era of American cars are famously still seen in Havana?',type:ChallengeType.typeIn,answer:'1950s',hint:'Left over from before the US embargo'),
    ]),
    Nation(id:'ca',name:'Canada',emoji:'🇨🇦',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Canada?',type:ChallengeType.mcq,answer:'Ottawa',options:['Toronto','Vancouver','Ottawa','Montreal']),
      Challenge(text:'Canada is the world\'s second largest country by what measure?',type:ChallengeType.mcq,answer:'Total area',options:['Population','GDP','Total area','Coastline length']),
      Challenge(text:'What is Canada\'s most popular national winter sport?',type:ChallengeType.mcq,answer:'Ice Hockey',options:['Curling','Ice Hockey','Skiing','Lacrosse']),
      Challenge(text:'What is the currency of Canada?',type:ChallengeType.typeIn,answer:'Canadian Dollar',hint:'Sometimes called the Loonie'),
      Challenge(text:'What is Canada\'s first and most famous national park in Alberta?',type:ChallengeType.typeIn,answer:'Banff',hint:'Established 1885, known for turquoise lakes'),
    ]),
    Nation(id:'pa',name:'Panama',emoji:'🇵🇦',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Panama?',type:ChallengeType.mcq,answer:'Panama City',options:['Colón','David','Santiago','Panama City']),
      Challenge(text:'The Panama Canal connects which two oceans?',type:ChallengeType.mcq,answer:'Pacific and Atlantic',options:['Pacific and Arctic','Indian and Pacific','Pacific and Atlantic','Atlantic and Arctic']),
      Challenge(text:'What is the currency of Panama?',type:ChallengeType.mcq,answer:'Balboa / US Dollar',options:['Colón','Peso','Quetzal','Balboa / US Dollar']),
      Challenge(text:'Panama hats actually originate from which country?',type:ChallengeType.typeIn,answer:'Ecuador',hint:'Woven in Ecuador, made famous via Panama'),
      Challenge(text:'What narrow land bridge does Panama sit on?',type:ChallengeType.typeIn,answer:'Isthmus of Panama',hint:'Connects North and South America'),
    ]),
    Nation(id:'cr',name:'Costa Rica',emoji:'🇨🇷',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Costa Rica?',type:ChallengeType.mcq,answer:'San José',options:['Liberia','Cartago','Alajuela','San José']),
      Challenge(text:'Costa Rica is famous for which type of sustainable tourism?',type:ChallengeType.mcq,answer:'Ecotourism',options:['Beach tourism','City tourism','Ecotourism','Heritage tourism']),
      Challenge(text:'Most of Costa Rica\'s electricity comes from which source?',type:ChallengeType.mcq,answer:'Renewable energy',options:['Coal','Nuclear','Renewable energy','Natural gas']),
      Challenge(text:'What is the currency of Costa Rica?',type:ChallengeType.typeIn,answer:'Colón',hint:'Named after Christopher Columbus'),
      Challenge(text:'What active volcano near San José has one of the world\'s widest craters?',type:ChallengeType.typeIn,answer:'Poás Volcano',hint:'In the Central Volcanic Range'),
    ]),
    Nation(id:'jm',name:'Jamaica',emoji:'🇯🇲',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Jamaica?',type:ChallengeType.mcq,answer:'Kingston',options:['Montego Bay','Negril','Ocho Rios','Kingston']),
      Challenge(text:'Jamaica is the birthplace of which music genre?',type:ChallengeType.mcq,answer:'Reggae',options:['Calypso','Reggae','Salsa','Soca']),
      Challenge(text:'What is the national dish of Jamaica?',type:ChallengeType.mcq,answer:'Ackee and Saltfish',options:['Jerk Chicken','Rice and Peas','Ackee and Saltfish','Oxtail Stew']),
      Challenge(text:'Which iconic reggae musician was born in Jamaica?',type:ChallengeType.typeIn,answer:'Bob Marley',hint:'From Trenchtown, Kingston'),
      Challenge(text:'What is the currency of Jamaica?',type:ChallengeType.typeIn,answer:'Jamaican Dollar',hint:'Abbreviated JMD'),
    ]),
    Nation(id:'ht',name:'Haiti',emoji:'🇭🇹',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Haiti?',type:ChallengeType.mcq,answer:'Port-au-Prince',options:['Cap-Haïtien','Jacmel','Gonaïves','Port-au-Prince']),
      Challenge(text:'Haiti became the first Black republic in which year?',type:ChallengeType.mcq,answer:'1804',options:['1776','1804','1820','1865']),
      Challenge(text:'What is Haiti\'s official language alongside French?',type:ChallengeType.mcq,answer:'Haitian Creole',options:['Spanish','Haitian Creole','English','Dutch']),
      Challenge(text:'What is the currency of Haiti?',type:ChallengeType.typeIn,answer:'Gourde',hint:'Abbreviated HTG'),
      Challenge(text:'What nation shares the island of Hispaniola with Haiti?',type:ChallengeType.typeIn,answer:'Dominican Republic',hint:'Haiti occupies the western third'),
    ]),
    Nation(id:'gt',name:'Guatemala',emoji:'🇬🇹',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Guatemala?',type:ChallengeType.mcq,answer:'Guatemala City',options:['Antigua','Quetzaltenango','Flores','Guatemala City']),
      Challenge(text:'Guatemala was the heartland of which ancient civilisation?',type:ChallengeType.mcq,answer:'Maya',options:['Aztec','Olmec','Maya','Zapotec']),
      Challenge(text:'What is the currency of Guatemala?',type:ChallengeType.mcq,answer:'Quetzal',options:['Lempira','Colón','Quetzal','Peso']),
      Challenge(text:'What colonial UNESCO city in Guatemala was the former capital?',type:ChallengeType.typeIn,answer:'Antigua Guatemala',hint:'Nestled among volcanoes'),
      Challenge(text:'What volcanic lake is considered Guatemala\'s most scenic?',type:ChallengeType.typeIn,answer:'Lake Atitlán',hint:'Called the most beautiful lake in the world'),
    ]),
    Nation(id:'py',name:'Paraguay',emoji:'🇵🇾',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Paraguay?',type:ChallengeType.mcq,answer:'Asunción',options:['Ciudad del Este','Encarnación','Concepción','Asunción']),
      Challenge(text:'Paraguay has two official languages. Spanish and what other?',type:ChallengeType.mcq,answer:'Guaraní',options:['Quechua','Aymara','Guaraní','Portuguese']),
      Challenge(text:'What is the currency of Paraguay?',type:ChallengeType.mcq,answer:'Guaraní',options:['Lempira','Colón','Guaraní','Peso']),
      Challenge(text:'What massive hydroelectric dam is shared between Paraguay and Brazil?',type:ChallengeType.typeIn,answer:'Itaipu Dam',hint:'Was once the world\'s largest hydroelectric plant'),
      Challenge(text:'What river forms Paraguay\'s western border?',type:ChallengeType.typeIn,answer:'Paraguay River',hint:'Divides Paraguay from the Chaco'),
    ]),
    Nation(id:'uy',name:'Uruguay',emoji:'🇺🇾',region:GlobeRegion.americas,challenges:[
      Challenge(text:'What is the capital of Uruguay?',type:ChallengeType.mcq,answer:'Montevideo',options:['Salto','Paysandú','Colonia','Montevideo']),
      Challenge(text:'Uruguay was the first Latin American country to legalise which substance?',type:ChallengeType.mcq,answer:'Cannabis',options:['Alcohol','Cannabis','Gambling','Same-sex marriage']),
      Challenge(text:'Uruguay shares its eastern border entirely with which country?',type:ChallengeType.mcq,answer:'Brazil',options:['Argentina','Chile','Brazil','Paraguay']),
      Challenge(text:'What is the currency of Uruguay?',type:ChallengeType.typeIn,answer:'Uruguayan Peso',hint:'Abbreviated UYU'),
      Challenge(text:'What is the world\'s oldest active football stadium, in Montevideo?',type:ChallengeType.typeIn,answer:'Estadio Centenario',hint:'Built for the 1930 FIFA World Cup'),
    ]),
  ];

  static const _asia = [
    Nation(id:'cn',name:'China',emoji:'🇨🇳',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of China?',type:ChallengeType.mcq,answer:'Beijing',options:['Shanghai','Guangzhou','Beijing','Chengdu']),
      Challenge(text:'What ancient structure stretches across northern China?',type:ChallengeType.mcq,answer:'Great Wall of China',options:['Silk Road','Great Wall of China','Grand Canal','Ming Tombs']),
      Challenge(text:'What is the currency of China?',type:ChallengeType.mcq,answer:'Renminbi (Yuan)',options:['Yen','Won','Renminbi (Yuan)','Rupee']),
      Challenge(text:'What is China\'s longest river, home to the Three Gorges Dam?',type:ChallengeType.typeIn,answer:'Yangtze River',hint:'Also called the Chang Jiang'),
      Challenge(text:'What ancient trade network connected China to Europe?',type:ChallengeType.typeIn,answer:'Silk Road',hint:'Named after China\'s famous export'),
    ]),
    Nation(id:'jp',name:'Japan',emoji:'🇯🇵',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Japan?',type:ChallengeType.mcq,answer:'Tokyo',options:['Osaka','Kyoto','Tokyo','Hiroshima']),
      Challenge(text:'What type of volcano is Japan\'s Mount Fuji?',type:ChallengeType.mcq,answer:'Stratovolcano',options:['Plateau','Shield volcano','Stratovolcano','Caldera']),
      Challenge(text:'What is the currency of Japan?',type:ChallengeType.mcq,answer:'Yen',options:['Won','Yen','Yuan','Baht']),
      Challenge(text:'What Japanese art of paper folding is popular worldwide?',type:ChallengeType.typeIn,answer:'Origami',hint:'From "oru" (fold) and "kami" (paper)'),
      Challenge(text:'What fast train system is Japan famous for?',type:ChallengeType.typeIn,answer:'Shinkansen',hint:'Also called the bullet train'),
    ]),
    Nation(id:'in',name:'India',emoji:'🇮🇳',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of India?',type:ChallengeType.mcq,answer:'New Delhi',options:['Mumbai','Kolkata','Chennai','New Delhi']),
      Challenge(text:'What iconic white marble mausoleum is in Agra, India?',type:ChallengeType.mcq,answer:'Taj Mahal',options:['Red Fort','Taj Mahal','Qutub Minar','Hawa Mahal']),
      Challenge(text:'What is the currency of India?',type:ChallengeType.mcq,answer:'Rupee',options:['Rupee','Taka','Baht','Kyat']),
      Challenge(text:'What river is sacred in Hinduism and flows through northern India?',type:ChallengeType.typeIn,answer:'Ganges',hint:'Also called Ganga'),
      Challenge(text:'What is the name of India\'s ancient epic featuring Arjuna and Krishna?',type:ChallengeType.typeIn,answer:'Mahabharata',hint:'The world\'s longest epic poem'),
    ]),
    Nation(id:'id',name:'Indonesia',emoji:'🇮🇩',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Indonesia?',type:ChallengeType.mcq,answer:'Jakarta',options:['Surabaya','Bandung','Bali','Jakarta']),
      Challenge(text:'Indonesia is the world\'s largest archipelago nation. True or False?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What island in Indonesia is famous for its Hindu culture and rice terraces?',type:ChallengeType.mcq,answer:'Bali',options:['Java','Bali','Sumatra','Lombok']),
      Challenge(text:'What is the currency of Indonesia?',type:ChallengeType.typeIn,answer:'Rupiah',hint:'Abbreviated IDR'),
      Challenge(text:'What great ape lives only in the rainforests of Borneo and Sumatra?',type:ChallengeType.typeIn,answer:'Orangutan',hint:'Malay for "person of the forest"'),
    ]),
    Nation(id:'th',name:'Thailand',emoji:'🇹🇭',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Thailand?',type:ChallengeType.mcq,answer:'Bangkok',options:['Chiang Mai','Pattaya','Phuket','Bangkok']),
      Challenge(text:'Thailand is the only Southeast Asian country never colonised by Europeans. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Thailand?',type:ChallengeType.mcq,answer:'Baht',options:['Ringgit','Baht','Dong','Kyat']),
      Challenge(text:'What ancient kingdom preceded Thailand, centred in Ayutthaya?',type:ChallengeType.typeIn,answer:'Ayutthaya Kingdom',hint:'Flourished from 1350 to 1767'),
      Challenge(text:'What spicy Thai salad is made from green papaya?',type:ChallengeType.typeIn,answer:'Som Tum',hint:'Also called papaya salad'),
    ]),
    Nation(id:'vn',name:'Vietnam',emoji:'🇻🇳',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Vietnam?',type:ChallengeType.mcq,answer:'Hanoi',options:['Ho Chi Minh City','Da Nang','Hue','Hanoi']),
      Challenge(text:'What is the currency of Vietnam?',type:ChallengeType.mcq,answer:'Dong',options:['Kip','Baht','Dong','Riel']),
      Challenge(text:'Ha Long Bay in Vietnam is famous for its limestone karst islands. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What popular Vietnamese noodle soup is served with broth and herbs?',type:ChallengeType.typeIn,answer:'Pho',hint:'Pronounced "fuh"'),
      Challenge(text:'What conical palm-leaf hat is a traditional Vietnamese symbol?',type:ChallengeType.typeIn,answer:'Nón lá',hint:'Worn by farmers in the fields'),
    ]),
    Nation(id:'ph',name:'Philippines',emoji:'🇵🇭',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of the Philippines?',type:ChallengeType.mcq,answer:'Manila',options:['Cebu','Davao','Manila','Quezon City']),
      Challenge(text:'The Philippines is an archipelago of approximately how many islands?',type:ChallengeType.mcq,answer:'7,641',options:['1,200','3,500','7,641','12,000']),
      Challenge(text:'The Philippines was colonised for 333 years by which country?',type:ChallengeType.mcq,answer:'Spain',options:['Portugal','United States','Spain','Netherlands']),
      Challenge(text:'What is the currency of the Philippines?',type:ChallengeType.typeIn,answer:'Philippine Peso',hint:'Abbreviated PHP'),
      Challenge(text:'What tiny but dangerous volcano sits on an island within a lake in the Philippines?',type:ChallengeType.typeIn,answer:'Taal Volcano',hint:'An island within a lake within an island'),
    ]),
    Nation(id:'pk',name:'Pakistan',emoji:'🇵🇰',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Pakistan?',type:ChallengeType.mcq,answer:'Islamabad',options:['Karachi','Lahore','Islamabad','Peshawar']),
      Challenge(text:'Pakistan is home to K2, the world\'s second highest mountain. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Pakistan?',type:ChallengeType.mcq,answer:'Pakistani Rupee',options:['Taka','Pakistani Rupee','Afghani','Rial']),
      Challenge(text:'What ancient Indus Valley city in Pakistan\'s Sindh province is a UNESCO site?',type:ChallengeType.typeIn,answer:'Mohenjo-daro',hint:'One of the world\'s earliest urban settlements'),
      Challenge(text:'What mountain range in northern Pakistan is home to K2?',type:ChallengeType.typeIn,answer:'Karakoram',hint:'Several 8000m peaks are here'),
    ]),
    Nation(id:'bd',name:'Bangladesh',emoji:'🇧🇩',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Bangladesh?',type:ChallengeType.mcq,answer:'Dhaka',options:['Chittagong','Sylhet','Rajshahi','Dhaka']),
      Challenge(text:'Bangladesh is a leading exporter of which textile?',type:ChallengeType.mcq,answer:'Ready-made garments',options:['Silk','Ready-made garments','Jute only','Wool']),
      Challenge(text:'What big cat lives in the Sundarbans mangrove forest of Bangladesh?',type:ChallengeType.mcq,answer:'Bengal Tiger',options:['Snow Leopard','Clouded Leopard','Bengal Tiger','Asian Lion']),
      Challenge(text:'What is the currency of Bangladesh?',type:ChallengeType.typeIn,answer:'Taka',hint:'Abbreviated BDT'),
      Challenge(text:'What massive river delta, one of the world\'s largest, runs through Bangladesh?',type:ChallengeType.typeIn,answer:'Ganges-Brahmaputra Delta',hint:'Also called the Bengal Delta'),
    ]),
    Nation(id:'my',name:'Malaysia',emoji:'🇲🇾',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Malaysia?',type:ChallengeType.mcq,answer:'Kuala Lumpur',options:['George Town','Johor Bahru','Kuala Lumpur','Ipoh']),
      Challenge(text:'What twin skyscrapers in Kuala Lumpur were the world\'s tallest from 1998–2004?',type:ChallengeType.mcq,answer:'Petronas Twin Towers',options:['KL Tower','KLCC Towers','Petronas Twin Towers','Maxis Tower']),
      Challenge(text:'Malaysia is the world\'s second largest producer of which oil?',type:ChallengeType.mcq,answer:'Palm oil',options:['Crude oil','Palm oil','Coconut oil','Rubber']),
      Challenge(text:'What is the currency of Malaysia?',type:ChallengeType.typeIn,answer:'Ringgit',hint:'Abbreviated MYR'),
      Challenge(text:'What large island shared by Malaysia, Indonesia, and Brunei is the world\'s third largest?',type:ChallengeType.typeIn,answer:'Borneo',hint:'Home to endangered orangutans'),
    ]),
    Nation(id:'kr',name:'South Korea',emoji:'🇰🇷',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of South Korea?',type:ChallengeType.mcq,answer:'Seoul',options:['Busan','Incheon','Daegu','Seoul']),
      Challenge(text:'What Korean fermented cabbage dish is a cuisine staple?',type:ChallengeType.mcq,answer:'Kimchi',options:['Bibimbap','Tteokbokki','Kimchi','Doenjang']),
      Challenge(text:'South Korea is a leading exporter of which technology?',type:ChallengeType.mcq,answer:'Semiconductors',options:['Aircraft','Pharmaceuticals','Semiconductors','Textiles']),
      Challenge(text:'What is the currency of South Korea?',type:ChallengeType.typeIn,answer:'Won',hint:'Abbreviated KRW'),
      Challenge(text:'What South Korean cultural wave of music, TV, and beauty has spread globally?',type:ChallengeType.typeIn,answer:'Hallyu',hint:'Also called the Korean Wave'),
    ]),
    Nation(id:'sa',name:'Saudi Arabia',emoji:'🇸🇦',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Saudi Arabia?',type:ChallengeType.mcq,answer:'Riyadh',options:['Jeddah','Mecca','Medina','Riyadh']),
      Challenge(text:'What is the world\'s largest oil field, found in Saudi Arabia?',type:ChallengeType.mcq,answer:'Ghawar Field',options:['Burgan Field','Ghawar Field','Safaniya Field','Khurais Field']),
      Challenge(text:'Saudi Arabia is the birthplace of which religion?',type:ChallengeType.mcq,answer:'Islam',options:['Christianity','Judaism','Islam','Zoroastrianism']),
      Challenge(text:'What is the currency of Saudi Arabia?',type:ChallengeType.typeIn,answer:'Saudi Riyal',hint:'Abbreviated SAR'),
      Challenge(text:'What is the holiest city in Islam, located in Saudi Arabia?',type:ChallengeType.typeIn,answer:'Mecca',hint:'Destination of the annual Hajj pilgrimage'),
    ]),
    Nation(id:'ae',name:'UAE',emoji:'🇦🇪',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of the UAE?',type:ChallengeType.mcq,answer:'Abu Dhabi',options:['Dubai','Sharjah','Abu Dhabi','Ajman']),
      Challenge(text:'The UAE is a federation of how many emirates?',type:ChallengeType.mcq,answer:'Seven',options:['Five','Six','Seven','Eight']),
      Challenge(text:'What is the world\'s tallest building, located in Dubai?',type:ChallengeType.mcq,answer:'Burj Khalifa',options:['Burj Al Arab','Burj Khalifa','CITIC Tower','Makkah Clock Tower']),
      Challenge(text:'What is the currency of the UAE?',type:ChallengeType.typeIn,answer:'Dirham',hint:'Abbreviated AED'),
      Challenge(text:'What island in Abu Dhabi hosts the Louvre Abu Dhabi museum?',type:ChallengeType.typeIn,answer:'Saadiyat Island',hint:'Also called the Island of Happiness'),
    ]),
    Nation(id:'ir',name:'Iran',emoji:'🇮🇷',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Iran?',type:ChallengeType.mcq,answer:'Tehran',options:['Isfahan','Mashhad','Shiraz','Tehran']),
      Challenge(text:'Iran was historically known by which ancient name?',type:ChallengeType.mcq,answer:'Persia',options:['Mesopotamia','Persia','Babylon','Parthia']),
      Challenge(text:'What is the currency of Iran?',type:ChallengeType.mcq,answer:'Rial',options:['Dinar','Dirham','Rial','Riyal']),
      Challenge(text:'What ancient Persian palace complex near Shiraz is a UNESCO site?',type:ChallengeType.typeIn,answer:'Persepolis',hint:'Built by Darius the Great around 518 BC'),
      Challenge(text:'What body of water borders Iran to the south?',type:ChallengeType.typeIn,answer:'Persian Gulf',hint:'Also called the Arabian Gulf'),
    ]),
    Nation(id:'iq',name:'Iraq',emoji:'🇮🇶',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Iraq?',type:ChallengeType.mcq,answer:'Baghdad',options:['Basra','Mosul','Erbil','Baghdad']),
      Challenge(text:'Iraq is located in the region historically called what?',type:ChallengeType.mcq,answer:'Mesopotamia',options:['Persia','Mesopotamia','Anatolia','Levant']),
      Challenge(text:'What two major rivers flow through Iraq?',type:ChallengeType.mcq,answer:'Tigris and Euphrates',options:['Nile and Jordan','Tigris and Euphrates','Indus and Ganges','Amu and Syr Darya']),
      Challenge(text:'What is the currency of Iraq?',type:ChallengeType.typeIn,answer:'Iraqi Dinar',hint:'Abbreviated IQD'),
      Challenge(text:'What ancient city near Hillah, Iraq, had legendary Hanging Gardens?',type:ChallengeType.typeIn,answer:'Babylon',hint:'One of the wonders of the ancient world'),
    ]),
    Nation(id:'jo',name:'Jordan',emoji:'🇯🇴',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Jordan?',type:ChallengeType.mcq,answer:'Amman',options:['Aqaba','Irbid','Zarqa','Amman']),
      Challenge(text:'What ancient city carved into rose-red cliffs is Jordan\'s most famous site?',type:ChallengeType.mcq,answer:'Petra',options:['Jerash','Petra','Wadi Rum','Madaba']),
      Challenge(text:'The Dead Sea, the world\'s lowest point on land, borders Jordan to the west. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Jordan?',type:ChallengeType.typeIn,answer:'Jordanian Dinar',hint:'Abbreviated JOD'),
      Challenge(text:'What vast desert of pink sandstone in Jordan was used as a Mars film set?',type:ChallengeType.typeIn,answer:'Wadi Rum',hint:'Also called the Valley of the Moon'),
    ]),
    Nation(id:'kz',name:'Kazakhstan',emoji:'🇰🇿',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Kazakhstan?',type:ChallengeType.mcq,answer:'Astana',options:['Almaty','Shymkent','Karaganda','Astana']),
      Challenge(text:'Kazakhstan is the world\'s largest landlocked country. True or False?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Kazakhstan?',type:ChallengeType.mcq,answer:'Tenge',options:['Som','Tenge','Manat','Lari']),
      Challenge(text:'What Soviet-era space launch facility is in Kazakhstan?',type:ChallengeType.typeIn,answer:'Baikonur Cosmodrome',hint:'Where Gagarin launched in 1961'),
      Challenge(text:'What large lake, once the world\'s fourth largest, has largely dried up in Kazakhstan?',type:ChallengeType.typeIn,answer:'Aral Sea',hint:'A 20th century ecological disaster'),
    ]),
    Nation(id:'uz',name:'Uzbekistan',emoji:'🇺🇿',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Uzbekistan?',type:ChallengeType.mcq,answer:'Tashkent',options:['Samarkand','Bukhara','Namangan','Tashkent']),
      Challenge(text:'Uzbekistan was a key country on which ancient trade network?',type:ChallengeType.mcq,answer:'Silk Road',options:['Spice Route','Silk Road','Amber Road','Incense Trail']),
      Challenge(text:'What ancient city in Uzbekistan was Tamerlane\'s imperial capital?',type:ChallengeType.mcq,answer:'Samarkand',options:['Bukhara','Khiva','Tashkent','Samarkand']),
      Challenge(text:'What is the currency of Uzbekistan?',type:ChallengeType.typeIn,answer:'Som',hint:'Abbreviated UZS'),
      Challenge(text:'What iconic tiled square in Samarkand is Uzbekistan\'s most famous landmark?',type:ChallengeType.typeIn,answer:'Registan',hint:'Means "sandy place" in Persian'),
    ]),
    Nation(id:'ge',name:'Georgia',emoji:'🇬🇪',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Georgia?',type:ChallengeType.mcq,answer:'Tbilisi',options:['Kutaisi','Batumi','Rustavi','Tbilisi']),
      Challenge(text:'Georgia is one of the world\'s oldest wine-producing regions. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What mountain range runs along Georgia\'s northern border?',type:ChallengeType.mcq,answer:'Greater Caucasus',options:['Pontic Alps','Greater Caucasus','Zagros','Taurus']),
      Challenge(text:'What is the currency of Georgia?',type:ChallengeType.typeIn,answer:'Lari',hint:'Abbreviated GEL'),
      Challenge(text:'What unique alphabet is used for the Georgian language?',type:ChallengeType.typeIn,answer:'Mkhedruli',hint:'One of the world\'s most distinctive scripts'),
    ]),
    Nation(id:'am',name:'Armenia',emoji:'🇦🇲',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Armenia?',type:ChallengeType.mcq,answer:'Yerevan',options:['Gyumri','Vanadzor','Vagharshapat','Yerevan']),
      Challenge(text:'Armenia was the first country to adopt which religion as a state religion?',type:ChallengeType.mcq,answer:'Christianity',options:['Islam','Christianity','Zoroastrianism','Judaism']),
      Challenge(text:'What sacred mountain visible from Yerevan is Armenia\'s national symbol?',type:ChallengeType.mcq,answer:'Mount Ararat',options:['Mount Ararat','Mount Aragats','Mount Azhdahak','Mount Kaputan']),
      Challenge(text:'What is the currency of Armenia?',type:ChallengeType.typeIn,answer:'Dram',hint:'Abbreviated AMD'),
      Challenge(text:'What ancient Hellenistic temple near Yerevan was built in the 1st century AD?',type:ChallengeType.typeIn,answer:'Garni Temple',hint:'Pagan temple, uniquely survived in Armenia'),
    ]),
    Nation(id:'mn',name:'Mongolia',emoji:'🇲🇳',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Mongolia?',type:ChallengeType.mcq,answer:'Ulaanbaatar',options:['Darkhan','Erdenet','Choibalsan','Ulaanbaatar']),
      Challenge(text:'Which great conqueror founded the Mongol Empire in the 13th century?',type:ChallengeType.mcq,answer:'Genghis Khan',options:['Kublai Khan','Timur','Genghis Khan','Ögedei Khan']),
      Challenge(text:'What desert covers much of southern Mongolia?',type:ChallengeType.mcq,answer:'Gobi',options:['Karakum','Gobi','Taklamakan','Kavir']),
      Challenge(text:'What is the currency of Mongolia?',type:ChallengeType.typeIn,answer:'Tögrög',hint:'Also spelled Tugrik, abbreviated MNT'),
      Challenge(text:'What traditional portable dwelling do Mongolian nomads live in?',type:ChallengeType.typeIn,answer:'Ger',hint:'Also called a yurt in Turkish'),
    ]),
    Nation(id:'np',name:'Nepal',emoji:'🇳🇵',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Nepal?',type:ChallengeType.mcq,answer:'Kathmandu',options:['Pokhara','Lalitpur','Biratnagar','Kathmandu']),
      Challenge(text:'Nepal is home to the world\'s highest peak. What is it called?',type:ChallengeType.mcq,answer:'Mount Everest',options:['K2','Kangchenjunga','Mount Everest','Lhotse']),
      Challenge(text:'What is the currency of Nepal?',type:ChallengeType.mcq,answer:'Nepalese Rupee',options:['Rupee','Taka','Nepalese Rupee','Ngultrum']),
      Challenge(text:'Which religion was founded by Siddhartha Gautama, born in Lumbini, Nepal?',type:ChallengeType.typeIn,answer:'Buddhism',hint:'Founded in the 5th century BCE'),
      Challenge(text:'What indigenous guides are famous for high-altitude mountaineering in Nepal?',type:ChallengeType.typeIn,answer:'Sherpa',hint:'Their name is now synonymous with mountain guiding'),
    ]),
    Nation(id:'mm',name:'Myanmar',emoji:'🇲🇲',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Myanmar?',type:ChallengeType.mcq,answer:'Naypyidaw',options:['Yangon','Mandalay','Bago','Naypyidaw']),
      Challenge(text:'Myanmar is famous for thousands of ancient Buddhist temples in which plain?',type:ChallengeType.mcq,answer:'Bagan',options:['Inle','Bagan','Ayeyarwady','Shan']),
      Challenge(text:'What is the currency of Myanmar?',type:ChallengeType.mcq,answer:'Kyat',options:['Kip','Riel','Kyat','Baht']),
      Challenge(text:'What is the former colonial name of Myanmar\'s largest city, Yangon?',type:ChallengeType.typeIn,answer:'Rangoon',hint:'Used during British rule'),
      Challenge(text:'What large freshwater lake in Myanmar\'s Shan State has unique floating gardens?',type:ChallengeType.typeIn,answer:'Inle Lake',hint:'Fishermen here row with one leg'),
    ]),
    Nation(id:'bt',name:'Bhutan',emoji:'🇧🇹',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Bhutan?',type:ChallengeType.mcq,answer:'Thimphu',options:['Paro','Punakha','Wangdue','Thimphu']),
      Challenge(text:'Bhutan measures national progress by Gross National Happiness instead of GDP. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Bhutan?',type:ChallengeType.mcq,answer:'Ngultrum',options:['Taka','Rupee','Kyat','Ngultrum']),
      Challenge(text:'What iconic cliff-side monastery in Paro is Bhutan\'s most visited landmark?',type:ChallengeType.typeIn,answer:'Tiger\'s Nest',hint:'Also called Paro Taktsang'),
      Challenge(text:'Bhutan absorbs more CO₂ than it emits, making it carbon what?',type:ChallengeType.typeIn,answer:'Carbon negative',hint:'Its forests absorb far more than the country produces'),
    ]),
    Nation(id:'mv',name:'Maldives',emoji:'🇲🇻',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of the Maldives?',type:ChallengeType.mcq,answer:'Malé',options:['Addu City','Fuvahmulah','Malé','Kulhudhuffushi']),
      Challenge(text:'The Maldives is the world\'s lowest-lying country at around how many metres average elevation?',type:ChallengeType.mcq,answer:'1.5 metres',options:['0.5 metres','1.5 metres','3 metres','5 metres']),
      Challenge(text:'What type of island formation makes up the Maldives?',type:ChallengeType.mcq,answer:'Coral atolls',options:['Volcanic islands','Granite islands','Coral atolls','Sand dunes']),
      Challenge(text:'What is the currency of the Maldives?',type:ChallengeType.typeIn,answer:'Rufiyaa',hint:'Abbreviated MVR'),
      Challenge(text:'Rising sea levels threaten to submerge the Maldives by end of this century. What is this threat called?',type:ChallengeType.typeIn,answer:'Climate change',hint:'The Maldives could become uninhabitable'),
    ]),
    Nation(id:'kg',name:'Kyrgyzstan',emoji:'🇰🇬',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Kyrgyzstan?',type:ChallengeType.mcq,answer:'Bishkek',options:['Osh','Jalal-Abad','Tokmok','Bishkek']),
      Challenge(text:'Kyrgyzstan is famous for which type of dramatic landscape?',type:ChallengeType.mcq,answer:'Mountain valleys',options:['Desert dunes','Tropical forest','Mountain valleys','Flat steppes']),
      Challenge(text:'What is the currency of Kyrgyzstan?',type:ChallengeType.mcq,answer:'Som',options:['Tenge','Manat','Som','Lari']),
      Challenge(text:'What alpine lake in Kyrgyzstan is one of the world\'s largest mountain lakes and never freezes?',type:ChallengeType.typeIn,answer:'Issyk-Kul',hint:'Means "warm lake"'),
      Challenge(text:'What nomadic dwelling appears on the Kyrgyz flag?',type:ChallengeType.typeIn,answer:'Yurt',hint:'The roof (tunduk) is depicted on the flag'),
    ]),
    Nation(id:'tj',name:'Tajikistan',emoji:'🇹🇯',region:GlobeRegion.asia,challenges:[
      Challenge(text:'What is the capital of Tajikistan?',type:ChallengeType.mcq,answer:'Dushanbe',options:['Khujand','Kulob','Qurghonteppa','Dushanbe']),
      Challenge(text:'Which mountain range covers most of Tajikistan?',type:ChallengeType.mcq,answer:'Pamir Mountains',options:['Tian Shan','Karakoram','Pamir Mountains','Hindu Kush']),
      Challenge(text:'What is the currency of Tajikistan?',type:ChallengeType.mcq,answer:'Somoni',options:['Som','Tenge','Somoni','Manat']),
      Challenge(text:'What narrow strip of Tajikistan borders Afghanistan and was a historic buffer zone?',type:ChallengeType.typeIn,answer:'Wakhan Corridor',hint:'Used during the Great Game between Russia and Britain'),
      Challenge(text:'What high plateau in Tajikistan is called the "Roof of the World"?',type:ChallengeType.typeIn,answer:'Pamir Plateau',hint:'Average elevation exceeds 4,000 metres'),
    ]),
  ];

  static const _europe = [
    Nation(id:'fr',name:'France',emoji:'🇫🇷',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of France?',type:ChallengeType.mcq,answer:'Paris',options:['Lyon','Marseille','Paris','Bordeaux']),
      Challenge(text:'What iconic iron tower stands in Paris?',type:ChallengeType.mcq,answer:'Eiffel Tower',options:['Arc de Triomphe','Notre-Dame','Eiffel Tower','Louvre']),
      Challenge(text:'What is the currency of France?',type:ChallengeType.mcq,answer:'Euro',options:['Franc','Euro','Pound','Mark']),
      Challenge(text:'What art museum in Paris is the world\'s most visited?',type:ChallengeType.typeIn,answer:'Louvre',hint:'Home of the Mona Lisa'),
      Challenge(text:'What annual bicycle race held in France covers approximately 3,500 km?',type:ChallengeType.typeIn,answer:'Tour de France',hint:'World\'s most prestigious cycling event'),
    ]),
    Nation(id:'de',name:'Germany',emoji:'🇩🇪',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Germany?',type:ChallengeType.mcq,answer:'Berlin',options:['Munich','Hamburg','Frankfurt','Berlin']),
      Challenge(text:'Which classical composer, born in 1770, was German?',type:ChallengeType.mcq,answer:'Beethoven',options:['Bach','Mozart','Beethoven','Brahms']),
      Challenge(text:'What is the currency of Germany?',type:ChallengeType.mcq,answer:'Euro',options:['Mark','Euro','Thaler','Pfennig']),
      Challenge(text:'What major river runs through Germany and empties into the North Sea?',type:ChallengeType.typeIn,answer:'Rhine',hint:'Also forms the German-French border'),
      Challenge(text:'What annual beer festival in Munich is the world\'s largest folk festival?',type:ChallengeType.typeIn,answer:'Oktoberfest',hint:'Runs from late September to early October'),
    ]),
    Nation(id:'it',name:'Italy',emoji:'🇮🇹',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Italy?',type:ChallengeType.mcq,answer:'Rome',options:['Milan','Naples','Rome','Florence']),
      Challenge(text:'What amphitheatre in Rome was completed in 80 AD?',type:ChallengeType.mcq,answer:'Colosseum',options:['Pantheon','Forum','Colosseum','Circus Maximus']),
      Challenge(text:'What is the currency of Italy?',type:ChallengeType.mcq,answer:'Euro',options:['Lira','Euro','Franc','Drachma']),
      Challenge(text:'What leaning medieval tower is found in Pisa, Italy?',type:ChallengeType.typeIn,answer:'Leaning Tower of Pisa',hint:'Campanile that tilts due to soft soil'),
      Challenge(text:'What Italian pasta dish uses spaghetti, eggs, pecorino, and guanciale?',type:ChallengeType.typeIn,answer:'Carbonara',hint:'A Roman specialty'),
    ]),
    Nation(id:'es',name:'Spain',emoji:'🇪🇸',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Spain?',type:ChallengeType.mcq,answer:'Madrid',options:['Barcelona','Seville','Madrid','Valencia']),
      Challenge(text:'What Spanish dance originated in Andalusia, with guitar and stamping?',type:ChallengeType.mcq,answer:'Flamenco',options:['Salsa','Tango','Flamenco','Paso Doble']),
      Challenge(text:'What is the currency of Spain?',type:ChallengeType.mcq,answer:'Euro',options:['Peseta','Euro','Real','Escudo']),
      Challenge(text:'What surrealist museum in Figueres is dedicated to a famous Catalan artist?',type:ChallengeType.typeIn,answer:'Dalí Theatre-Museum',hint:'Named after Salvador Dalí'),
      Challenge(text:'What annual tomato-throwing festival is held in Buñol, Spain?',type:ChallengeType.typeIn,answer:'La Tomatina',hint:'Held on the last Wednesday of August'),
    ]),
    Nation(id:'pt',name:'Portugal',emoji:'🇵🇹',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Portugal?',type:ChallengeType.mcq,answer:'Lisbon',options:['Porto','Braga','Coimbra','Lisbon']),
      Challenge(text:'Portugal pioneered global exploration and its first maritime trading empire. True?',type:ChallengeType.mcq,answer:'True',options:['True','False']),
      Challenge(text:'What is the currency of Portugal?',type:ChallengeType.mcq,answer:'Euro',options:['Escudo','Euro','Real','Peseta']),
      Challenge(text:'What melancholic music genre is associated with Lisbon\'s old neighbourhoods?',type:ChallengeType.typeIn,answer:'Fado',hint:'Meaning "fate" in Portuguese'),
      Challenge(text:'What iconic custard tart was invented by monks in Lisbon\'s Belém district?',type:ChallengeType.typeIn,answer:'Pastel de nata',hint:'Also called Pastéis de Belém'),
    ]),
    Nation(id:'gr',name:'Greece',emoji:'🇬🇷',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Greece?',type:ChallengeType.mcq,answer:'Athens',options:['Thessaloniki','Patras','Heraklion','Athens']),
      Challenge(text:'What ancient hilltop fortress in Athens houses the Parthenon?',type:ChallengeType.mcq,answer:'Acropolis',options:['Acropolis','Agora','Kerameikos','Olympieion']),
      Challenge(text:'What is the currency of Greece?',type:ChallengeType.mcq,answer:'Euro',options:['Drachma','Euro','Lira','Mark']),
      Challenge(text:'What ancient city-state was famous for its warrior culture?',type:ChallengeType.typeIn,answer:'Sparta',hint:'Rivals of Athens, in the Peloponnese'),
      Challenge(text:'What sea lies to the east of mainland Greece?',type:ChallengeType.typeIn,answer:'Aegean Sea',hint:'Named perhaps after mythical king Aegeus'),
    ]),
    Nation(id:'nl',name:'Netherlands',emoji:'🇳🇱',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of the Netherlands?',type:ChallengeType.mcq,answer:'Amsterdam',options:['Rotterdam','The Hague','Utrecht','Amsterdam']),
      Challenge(text:'What flood-control structures is the Netherlands most famous for?',type:ChallengeType.mcq,answer:'Dykes and windmills',options:['Levees and canals','Dykes and windmills','Seawalls and pumps','Tidal barriers']),
      Challenge(text:'What is the currency of the Netherlands?',type:ChallengeType.mcq,answer:'Euro',options:['Guilder','Euro','Franc','Krone']),
      Challenge(text:'What Dutch artist painted "The Night Watch" in 1642?',type:ChallengeType.typeIn,answer:'Rembrandt',hint:'Housed in the Rijksmuseum, Amsterdam'),
      Challenge(text:'What famous bulb flower is exported in vast quantities from the Netherlands?',type:ChallengeType.typeIn,answer:'Tulip',hint:'Fields bloom every spring in Lisse'),
    ]),
    Nation(id:'pl',name:'Poland',emoji:'🇵🇱',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Poland?',type:ChallengeType.mcq,answer:'Warsaw',options:['Kraków','Gdańsk','Łódź','Warsaw']),
      Challenge(text:'What is the currency of Poland?',type:ChallengeType.mcq,answer:'Złoty',options:['Euro','Forint','Złoty','Koruna']),
      Challenge(text:'What Polish city is famous for its medieval town square and Wawel Castle?',type:ChallengeType.mcq,answer:'Kraków',options:['Gdańsk','Wrocław','Kraków','Poznań']),
      Challenge(text:'What Polish astronomer proposed the heliocentric model of the solar system?',type:ChallengeType.typeIn,answer:'Copernicus',hint:'Born in Toruń in 1473'),
      Challenge(text:'What WWII Nazi extermination camp in Poland is now a UNESCO memorial?',type:ChallengeType.typeIn,answer:'Auschwitz',hint:'Near Oświęcim in southern Poland'),
    ]),
    Nation(id:'se',name:'Sweden',emoji:'🇸🇪',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Sweden?',type:ChallengeType.mcq,answer:'Stockholm',options:['Gothenburg','Malmö','Uppsala','Stockholm']),
      Challenge(text:'What prestigious prizes including Peace and Literature are awarded annually in Sweden?',type:ChallengeType.mcq,answer:'Nobel Prizes',options:['Pulitzer Prizes','Nobel Prizes','Balzan Prizes','Kyoto Prize']),
      Challenge(text:'What is the currency of Sweden?',type:ChallengeType.mcq,answer:'Swedish Krona',options:['Euro','Norwegian Krone','Swedish Krona','Danish Krone']),
      Challenge(text:'What Swedish furniture giant is the world\'s largest furniture retailer?',type:ChallengeType.typeIn,answer:'IKEA',hint:'Founded by Ingvar Kamprad in 1943'),
      Challenge(text:'What Swedish pop group was one of the best-selling acts of the 1970s and 80s?',type:ChallengeType.typeIn,answer:'ABBA',hint:'Formed in Stockholm in 1972'),
    ]),
    Nation(id:'no',name:'Norway',emoji:'🇳🇴',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Norway?',type:ChallengeType.mcq,answer:'Oslo',options:['Bergen','Trondheim','Stavanger','Oslo']),
      Challenge(text:'Norway is famous for which narrow coastal inlets formed by glaciers?',type:ChallengeType.mcq,answer:'Fjords',options:['Fjords','Eskers','Moraines','Drumlins']),
      Challenge(text:'What is the currency of Norway?',type:ChallengeType.mcq,answer:'Norwegian Krone',options:['Euro','Swedish Krona','Norwegian Krone','Danish Krone']),
      Challenge(text:'What light phenomenon is visible in Norway\'s far north?',type:ChallengeType.typeIn,answer:'Northern Lights',hint:'Also called Aurora Borealis'),
      Challenge(text:'What Norwegian explorer was first to reach the South Pole in 1911?',type:ChallengeType.typeIn,answer:'Roald Amundsen',hint:'Beat Scott\'s British expedition by five weeks'),
    ]),
    Nation(id:'dk',name:'Denmark',emoji:'🇩🇰',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Denmark?',type:ChallengeType.mcq,answer:'Copenhagen',options:['Aarhus','Odense','Aalborg','Copenhagen']),
      Challenge(text:'Denmark controls which autonomous Arctic territory?',type:ChallengeType.mcq,answer:'Greenland',options:['Iceland','Faroe Islands','Greenland','Svalbard']),
      Challenge(text:'What is the currency of Denmark?',type:ChallengeType.mcq,answer:'Danish Krone',options:['Euro','Swedish Krona','Norwegian Krone','Danish Krone']),
      Challenge(text:'What Danish fairy tale author wrote "The Little Mermaid"?',type:ChallengeType.typeIn,answer:'Hans Christian Andersen',hint:'Born in Odense in 1805'),
      Challenge(text:'What iconic 1843 amusement park in central Copenhagen inspired Walt Disney?',type:ChallengeType.typeIn,answer:'Tivoli Gardens',hint:'One of the world\'s oldest amusement parks'),
    ]),
    Nation(id:'fi',name:'Finland',emoji:'🇫🇮',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Finland?',type:ChallengeType.mcq,answer:'Helsinki',options:['Tampere','Turku','Espoo','Helsinki']),
      Challenge(text:'Finland has approximately how many lakes?',type:ChallengeType.mcq,answer:'188,000',options:['10,000','50,000','188,000','500,000']),
      Challenge(text:'What is the currency of Finland?',type:ChallengeType.mcq,answer:'Euro',options:['Markka','Euro','Krone','Kroon']),
      Challenge(text:'What Finnish tradition involves bathing in a heated steam room?',type:ChallengeType.typeIn,answer:'Sauna',hint:'Finland has one for nearly every family'),
      Challenge(text:'What Finnish company famous for mobile phones was originally a paper mill?',type:ChallengeType.typeIn,answer:'Nokia',hint:'Founded in 1865'),
    ]),
    Nation(id:'at',name:'Austria',emoji:'🇦🇹',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Austria?',type:ChallengeType.mcq,answer:'Vienna',options:['Salzburg','Graz','Innsbruck','Vienna']),
      Challenge(text:'Austria was the heartland of which powerful European empire?',type:ChallengeType.mcq,answer:'Habsburg Empire',options:['Ottoman Empire','Habsburg Empire','Holy Roman Empire','Roman Empire']),
      Challenge(text:'What is the currency of Austria?',type:ChallengeType.mcq,answer:'Euro',options:['Schilling','Euro','Franc','Mark']),
      Challenge(text:'What famous composer was born in Salzburg, Austria in 1756?',type:ChallengeType.typeIn,answer:'Mozart',hint:'Full name: Wolfgang Amadeus Mozart'),
      Challenge(text:'What Austrian city twice hosted the Winter Olympics, in 1964 and 1976?',type:ChallengeType.typeIn,answer:'Innsbruck',hint:'Capital of Tyrol in western Austria'),
    ]),
    Nation(id:'be',name:'Belgium',emoji:'🇧🇪',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Belgium and headquarters of the EU?',type:ChallengeType.mcq,answer:'Brussels',options:['Ghent','Antwerp','Bruges','Brussels']),
      Challenge(text:'Belgium is world-famous for producing some of the best what?',type:ChallengeType.mcq,answer:'Chocolate',options:['Cheese','Chocolate','Wine','Beer only']),
      Challenge(text:'What is the currency of Belgium?',type:ChallengeType.mcq,answer:'Euro',options:['Franc','Euro','Mark','Guilder']),
      Challenge(text:'What 1815 battle near Brussels ended Napoleon\'s rule?',type:ChallengeType.typeIn,answer:'Battle of Waterloo',hint:'Wellington defeated Napoleon here'),
      Challenge(text:'What Belgian city famous for medieval canals is the "Venice of the North"?',type:ChallengeType.typeIn,answer:'Bruges',hint:'A UNESCO World Heritage city'),
    ]),
    Nation(id:'cz',name:'Czechia',emoji:'🇨🇿',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Czechia?',type:ChallengeType.mcq,answer:'Prague',options:['Brno','Ostrava','Plzeň','Prague']),
      Challenge(text:'Czechia is the world\'s largest per-capita consumer of what?',type:ChallengeType.mcq,answer:'Beer',options:['Wine','Beer','Coffee','Spirits']),
      Challenge(text:'What is the currency of Czechia?',type:ChallengeType.mcq,answer:'Czech Koruna',options:['Euro','Czech Koruna','Forint','Złoty']),
      Challenge(text:'What ancient astronomical clock in Prague\'s Old Town dates back to 1410?',type:ChallengeType.typeIn,answer:'Prague Orloj',hint:'The oldest working astronomical clock'),
      Challenge(text:'What Prague-born writer created "The Metamorphosis"?',type:ChallengeType.typeIn,answer:'Franz Kafka',hint:'Kafka\'s Castle and Trial are also masterworks'),
    ]),
    Nation(id:'hu',name:'Hungary',emoji:'🇭🇺',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Hungary?',type:ChallengeType.mcq,answer:'Budapest',options:['Debrecen','Miskolc','Pécs','Budapest']),
      Challenge(text:'Which river divides Budapest into Buda and Pest?',type:ChallengeType.mcq,answer:'Danube',options:['Tisza','Danube','Rhine','Elbe']),
      Challenge(text:'What is the currency of Hungary?',type:ChallengeType.mcq,answer:'Forint',options:['Euro','Leu','Forint','Koruna']),
      Challenge(text:'What spicy paprika meat stew is Hungary\'s national dish?',type:ChallengeType.typeIn,answer:'Goulash',hint:'Thick soup with vegetables and paprika'),
      Challenge(text:'What famous puzzle cube was invented by a Hungarian professor in 1974?',type:ChallengeType.typeIn,answer:'Rubik\'s Cube',hint:'Named after Ernő Rubik'),
    ]),
    Nation(id:'ro',name:'Romania',emoji:'🇷🇴',region:GlobeRegion.europe,challenges:[
      Challenge(text:'What is the capital of Romania?',type:ChallengeType.mcq,answer:'Bucharest',options:['Cluj-Napoca','Timișoara','Iași','Bucharest']),
      Challenge(text:'Romania\'s Transylvania region is associated with which fictional vampire?',type:ChallengeType.mcq,answer:'Dracula',options:['Frankenstein','Dracula','Van Helsing','Nosferatu']),
      Challenge(text:'What is the currency of Romania?',type:ChallengeType.mcq,answer:'Romanian Leu',options:['Euro','Forint','Romanian Leu','Lev']),
      Challenge(text:'What massive palace in Bucharest, built under Ceaușescu, is the world\'s heaviest building?',type:ChallengeType.typeIn,answer:'Palace of the Parliament',hint:'Has over 1,000 rooms'),
      Challenge(text:'What mountain range runs through central Romania?',type:ChallengeType.typeIn,answer:'Carpathian Mountains',hint:'Home of medieval castles and wolves'),
    ]),
  ];

  static const _oceania = [
    Nation(id:'au',name:'Australia',emoji:'🇦🇺',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Australia?',type:ChallengeType.mcq,answer:'Canberra',options:['Sydney','Melbourne','Brisbane','Canberra']),
      Challenge(text:'What large sandstone monolith is sacred to Aboriginal Australians?',type:ChallengeType.mcq,answer:'Uluru',options:['Uluru','Blue Mountains','Twelve Apostles','Bungle Bungles']),
      Challenge(text:'What is the currency of Australia?',type:ChallengeType.mcq,answer:'Australian Dollar',options:['Pound','Australian Dollar','NZ Dollar','Pacific Dollar']),
      Challenge(text:'What marsupial unique to Australia carries its young in a pouch?',type:ChallengeType.typeIn,answer:'Kangaroo',hint:'Australia\'s national animal alongside the emu'),
      Challenge(text:'What coral reef system off Queensland is the world\'s largest living structure?',type:ChallengeType.typeIn,answer:'Great Barrier Reef',hint:'Visible from space'),
    ]),
    Nation(id:'nz',name:'New Zealand',emoji:'🇳🇿',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of New Zealand?',type:ChallengeType.mcq,answer:'Wellington',options:['Auckland','Christchurch','Dunedin','Wellington']),
      Challenge(text:'What is the Māori name for New Zealand?',type:ChallengeType.mcq,answer:'Aotearoa',options:['Aotearoa','Te Waipounamu','Tangata Whenua','Motu']),
      Challenge(text:'New Zealand was the first country to give women the vote in which year?',type:ChallengeType.mcq,answer:'1893',options:['1893','1918','1928','1945']),
      Challenge(text:'What is the currency of New Zealand?',type:ChallengeType.typeIn,answer:'New Zealand Dollar',hint:'Abbreviated NZD'),
      Challenge(text:'What flightless bird is New Zealand\'s national animal?',type:ChallengeType.typeIn,answer:'Kiwi',hint:'Also slang for New Zealanders'),
    ]),
    Nation(id:'pg',name:'Papua New Guinea',emoji:'🇵🇬',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Papua New Guinea?',type:ChallengeType.mcq,answer:'Port Moresby',options:['Lae','Mount Hagen','Madang','Port Moresby']),
      Challenge(text:'PNG has extraordinary linguistic diversity with over how many languages?',type:ChallengeType.mcq,answer:'800+',options:['50','200','500','800+']),
      Challenge(text:'What is the currency of Papua New Guinea?',type:ChallengeType.mcq,answer:'Kina',options:['Dollar','Kina','Tālā','Vatu']),
      Challenge(text:'What large island does Papua New Guinea share with Indonesia?',type:ChallengeType.typeIn,answer:'New Guinea',hint:'Same name as the country without "Papua"'),
      Challenge(text:'What colourful native bird appears on PNG\'s national flag?',type:ChallengeType.typeIn,answer:'Bird of Paradise',hint:'Used in tribal dress too'),
    ]),
    Nation(id:'fj',name:'Fiji',emoji:'🇫🇯',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Fiji?',type:ChallengeType.mcq,answer:'Suva',options:['Nadi','Lautoka','Labasa','Suva']),
      Challenge(text:'Fiji is an archipelago of approximately how many islands?',type:ChallengeType.mcq,answer:'332',options:['50','150','332','700']),
      Challenge(text:'What is the currency of Fiji?',type:ChallengeType.mcq,answer:'Fijian Dollar',options:['Vatu','Tālā','Fijian Dollar','Franc']),
      Challenge(text:'What traditional Fijian drink is made from a pepper plant root?',type:ChallengeType.typeIn,answer:'Kava',hint:'Also called yaqona in Fiji'),
      Challenge(text:'What ocean surrounds Fiji?',type:ChallengeType.typeIn,answer:'Pacific Ocean',hint:'World\'s largest ocean'),
    ]),
    Nation(id:'ws',name:'Samoa',emoji:'🇼🇸',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Samoa?',type:ChallengeType.mcq,answer:'Apia',options:['Pago Pago','Salelologa','Faleolo','Apia']),
      Challenge(text:'What is the traditional Samoan full-body tattoo art called?',type:ChallengeType.mcq,answer:'Pe\'a',options:['Henna','Pe\'a','Tā moko','Sak yant']),
      Challenge(text:'What is the currency of Samoa?',type:ChallengeType.mcq,answer:'Tālā',options:['Dollar','Kina','Tālā','Vatu']),
      Challenge(text:'What is the traditional Samoan open-sided thatched house called?',type:ChallengeType.typeIn,answer:'Fale',hint:'Communal open-air structure'),
      Challenge(text:'What ocean surrounds Samoa?',type:ChallengeType.typeIn,answer:'Pacific Ocean',hint:'The largest ocean on Earth'),
    ]),
    Nation(id:'vu',name:'Vanuatu',emoji:'🇻🇺',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Vanuatu?',type:ChallengeType.mcq,answer:'Port Vila',options:['Luganville','Port Vila','Lakatoro','Isangel']),
      Challenge(text:'What is the currency of Vanuatu?',type:ChallengeType.mcq,answer:'Vatu',options:['Dollar','Kina','Tālā','Vatu']),
      Challenge(text:'Vanuatu has one of the world\'s most accessible active volcanoes on which island?',type:ChallengeType.mcq,answer:'Tanna Island',options:['Efate','Espiritu Santo','Tanna Island','Malakula']),
      Challenge(text:'What is the traditional land diving ceremony practised on Pentecost Island?',type:ChallengeType.typeIn,answer:'Naghol',hint:'Considered the origin of bungee jumping'),
      Challenge(text:'Vanuatu is an archipelago in which ocean?',type:ChallengeType.typeIn,answer:'Pacific Ocean',hint:'Southwest Pacific, near New Caledonia'),
    ]),
    Nation(id:'om',name:'Oman',emoji:'🇴🇲',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Oman?',type:ChallengeType.mcq,answer:'Muscat',options:['Salalah','Sohar','Nizwa','Muscat']),
      Challenge(text:'What body of water borders Oman to the east?',type:ChallengeType.mcq,answer:'Arabian Sea',options:['Red Sea','Arabian Sea','Persian Gulf','Indian Ocean only']),
      Challenge(text:'What is the currency of Oman?',type:ChallengeType.mcq,answer:'Omani Rial',options:['Dirham','Riyal','Omani Rial','Dinar']),
      Challenge(text:'What ancient aromatic trading commodity made Dhofar, Oman famous for millennia?',type:ChallengeType.typeIn,answer:'Frankincense',hint:'Used in religious ceremonies worldwide'),
      Challenge(text:'What is the name of Oman\'s dramatic canyon, the "Grand Canyon of Arabia"?',type:ChallengeType.typeIn,answer:'Wadi Ghul',hint:'In the Hajar Mountains, drops 1,000 metres'),
    ]),
    Nation(id:'kw',name:'Kuwait',emoji:'🇰🇼',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Kuwait?',type:ChallengeType.mcq,answer:'Kuwait City',options:['Ahmadi','Hawalli','Fahaheel','Kuwait City']),
      Challenge(text:'Kuwait\'s economy is largely based on which resource?',type:ChallengeType.mcq,answer:'Petroleum',options:['Fishing','Petroleum','Tourism','Agriculture']),
      Challenge(text:'What is the currency of Kuwait?',type:ChallengeType.mcq,answer:'Kuwaiti Dinar',options:['Riyal','Dirham','Kuwaiti Dinar','Rial']),
      Challenge(text:'Kuwait was liberated from Iraqi occupation after which war and in which year?',type:ChallengeType.typeIn,answer:'Gulf War 1991',hint:'Operation Desert Storm'),
      Challenge(text:'What large gulf borders Kuwait to the east?',type:ChallengeType.typeIn,answer:'Persian Gulf',hint:'Also called the Arabian Gulf'),
    ]),
    Nation(id:'bh',name:'Bahrain',emoji:'🇧🇭',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Bahrain?',type:ChallengeType.mcq,answer:'Manama',options:['Riffa','Muharraq','Hamad Town','Manama']),
      Challenge(text:'Bahrain is an archipelago of approximately how many islands?',type:ChallengeType.mcq,answer:'33',options:['12','33','75','100']),
      Challenge(text:'What is the currency of Bahrain?',type:ChallengeType.mcq,answer:'Bahraini Dinar',options:['Riyal','Dirham','Bahraini Dinar','Rial']),
      Challenge(text:'What is the name of Bahrain\'s ancient desert tree said to be over 400 years old with no apparent water source?',type:ChallengeType.typeIn,answer:'Tree of Life',hint:'A mesquite tree in the desert'),
      Challenge(text:'What Formula 1 circuit hosts the Bahrain Grand Prix?',type:ChallengeType.typeIn,answer:'Bahrain International Circuit',hint:'Located in Sakhir desert'),
    ]),
    Nation(id:'qa',name:'Qatar',emoji:'🇶🇦',region:GlobeRegion.oceania,challenges:[
      Challenge(text:'What is the capital of Qatar?',type:ChallengeType.mcq,answer:'Doha',options:['Al Wakrah','Al Rayyan','Doha','Lusail']),
      Challenge(text:'Qatar hosted the FIFA World Cup in which year?',type:ChallengeType.mcq,answer:'2022',options:['2018','2022','2026','2010']),
      Challenge(text:'What is the currency of Qatar?',type:ChallengeType.mcq,answer:'Qatari Riyal',options:['Dirham','Dinar','Qatari Riyal','Rial']),
      Challenge(text:'What global news network is headquartered in Doha, Qatar?',type:ChallengeType.typeIn,answer:'Al Jazeera',hint:'Launched in 1996, Arabic and English'),
      Challenge(text:'Qatar has enormous reserves of which fossil fuel alongside oil?',type:ChallengeType.typeIn,answer:'Natural gas',hint:'Shares the North Dome/South Pars field with Iran'),
    ]),
  ];
}
